### ISSUE TITLE
Add lazy loading or preloading to this react.js project

### ISSUE THREAD

**Issue by arpittyagirocks** [arpittyagirocks/Humari-Dukan#13]
Hello contributers, I want someone to add lazy loading or preloading animation to this react, reactjs project.

**Comment by Sky-De** [comment]
Hi there
Please assign this to me
Then I'll work on this
Ty

**Comment by arpittyagirocks** [comment]
I have assigned you the Issue
you can ask me, If you need any help.

**Comment by Pulkitxm** [comment]
Can I get assigned and tell me how to start ?

**Comment by arpittyagirocks** [comment]
Hello @Pulkitxm, to get started, you can take reference from [CONTRIBUTING.md](https://github.com/arpittyagirocks/Humari-Dukan/blob/master/CONTRIBUTING.md) file, do not hesitate to ask anything you don't understand.

**Comment by Pulkitxm** [comment]
Ok Please assign the issue to me

**Comment by arpittyagirocks** [comment]
This issue is already assigned to @Sky-De , and i am not sure if he is willing to work on this together.
- Find anything in the project you can add or improve  
- go to issues and create your own new issue, mentioning your idea or changes
- then fork the project, implement the changes and send the pull request

**Comment by Pulkitxm** [comment]
okay lemme know If I can proceed

**Comment by arpittyagirocks** [comment]
Yes, you can continue @Pulkitxm

**Comment by Sky-De** [comment]
Hi @arpittyagirocks
i was busy these days
so i just decided start working on this issue right now, but it seems  @Pulkitxm has started working on this, if not let me know to start, otherwise let me know then i have a chance to take a look at code.
thanks

**Comment by arpittyagirocks** [comment]
@Sky-De
he had actually solved this issue, please have look at the code to add or improve anything you can.
Thank you for your intrest
