### ISSUE TITLE
Improve and fix the carousal banner on the main page.

### ISSUE THREAD

**Issue by arpittyagirocks** [arpittyagirocks/Humari-Dukan#16]
Hello contributers, I have noticed that the carousal banner is too large and covering the whole screen for certain devices, Can someone fix it to look amazing and responsive in all devices?

**Comment by VIVEKIITdelhi** [comment]
Yes I can do this, you may assign this to me....

**Comment by VIVEKIITdelhi** [comment]
Are you talking about this issue....... 
![Screenshot (30)](https://github.com/arpittyagirocks/Humari-Dukan/assets/114601400/ff5076d9-309a-4be7-bbaa-de8184b7c05f)
